### PR TITLE
CLD-467: adding notice and license to the repo

### PR DESCRIPTION
**Pull request by barkhachoithani**

### CODE REVIEW

**Comment by vitalykorolev** [comment]
@barkhachoithani are txt extensions removed intentionally?

**Comment by jmckean17** [comment]
What is the difference between the Notice and the License? They look like they are duplicating information. Also, in the License, aren't we supposed to customize the license for our use as described at the end?

**Comment by barkhachoithani** [comment]
> @barkhachoithani are txt extensions removed intentionally?

Added txt extension to the files.

**Comment by vitalykorolev** [comment]
> What is the difference between the Notice and the License? They look like they are duplicating information. Also, in the License, aren't we supposed to customize the license for our use as described at the end?

@jmckean17 these documents are provided by the legal team as part of open source distribution. Looks like there are some differences in the files and you can ask Zak about specifics.

**Review by vitalykorolev — APPROVED** [review]

**Review by jmckean17 — APPROVED** [review]
See my note. If Legal provided the content for the Notice and the License, then I approved this content.

**Pull request merged**
